<div style=" background-color: RGB(0,114,200);" >
<h1 style="margin: auto; padding: 20px 0; color:#fff; text-align: center">PROJET 4 DATA ANALYST</h1>
<h2 style="margin: auto; padding: 20px 0; color:#fff; text-align: center">Réalisez une étude de santé publique avec R ou Python
</h2>
</div>

# OBJECTIF DE CE NOTEBOOK

Bienvenue dans l'outil plébiscité par les analystes de données Jupyter.

Il s'agit d'un outil permettant de mixer et d'alterner codes, textes et graphique.

Cet outil est formidable pour plusieurs raisons:

+ il permet de tester des lignes de codes au fur et à mesure de votre rédaction, de constater immédiatement le résultat d'un instruction, de la corriger si nécessaire.
+ De rédiger du texte pour expliquer l'approche suivie ou les résultats d'une analyse et de le mettre en forme grâce à du code html ou plus simple avec **Markdown**
+ d'agrémenter de graphiques

Pour vous aider dans vos premiers pas à l'usage de Jupyter et de Python, nous avons rédigé ce notebook en vous indiquant les instructions à suivre.

Il vous suffit pour cela de saisir le code Python répondant à l'instruction donnée.

Vous verrez de temps à autre le code Python répondant à une instruction donnée mais cela est fait pour vous aider à comprendre la nature du travail qui vous est demandée.

Et garder à l'esprit, qu'il n'y a pas de solution unique pour résoudre un problème et qu'il y a autant de résolutions de problèmes que de développeurs ;)...

<div style="background-color: RGB(0,150,250);" >
<h2 style="margin: auto; padding: 20px; color:#fff; ">Etape 1 - Importation des librairies et chargement des fichiers</h2>
</div>

<div style="border: 1px solid RGB(0,150,250);" >
<h3 style="margin: auto; padding: 20px; color: RGB(0,150,250); ">1.1 - Importation des librairies</h3>
</div>

In [62]:
#Importation de la librairie Pandas
import pandas as pd

<div style="border: 1px solid RGB(0,150,250);" >
<h3 style="margin: auto; padding: 20px; color: RGB(0,150,250); ">1.2 - Chargement des fichiers Excel</h3>
</div>

In [63]:
#Importation du fichier population.csv
population = pd.read_csv('../input/projet-4/population.csv')

#Importation du fichier dispo_alimentaire.csv
dispo_alimentaire = pd.read_csv('../input/projet-4/dispo_alimentaire.csv')

#Importation du fichier aide_alimentaire.csv
aide_alimentaire = pd.read_csv('../input/projet-4/aide_alimentaire.csv')

#Importation du fichier sous_nutrition.csv
sous_nutrition = pd.read_csv('../input/projet-4/sous_nutrition.csv')

In [64]:
#Importation de la librairie Pandas
import pandas as pd

<div style="background-color: RGB(0,150,250);" >
<h2 style="margin: auto; padding: 20px; color:#fff; ">Etape 2 - Analyse exploratoire des fichiers</h2>
</div>

<div style="border: 1px solid RGB(0,150,250);" >
<h3 style="margin: auto; padding: 20px; color: RGB(0,150,250); ">2.1 - Analyse exploratoire du fichier population</h3>
</div>

In [65]:
#Afficher les dimensions du dataset
print("Le tableau comporte {} observation(s) ou article(s)".format(population.shape[0]))
print("Le tableau comporte {} colonne(s)".format(population.shape[1]))

Le tableau comporte 1416 observation(s) ou article(s)
Le tableau comporte 3 colonne(s)

In [66]:
#Consulter le nombre de colonnes
nbr_col = population.shape
print("Le tableau comporte {} colonne(s)".format(nbr_col[1]))
#La nature des données dans chacune des colonnes
print("La nature des données dans chacune des colonnes:\n{}".format(population.dtypes))
#Le nombre de valeurs présentes dans chacune des colonnes
print("Le nombre de valeurs présentes dans chacune des colonnes:\n{}".format(population.count()))

Le tableau comporte 3 colonne(s)
La nature des données dans chacune des colonnes:
Zone       object
Année       int64
Valeur    float64
dtype: object
Le nombre de valeurs présentes dans chacune des colonnes:
Zone      1416
Année     1416
Valeur    1416
dtype: int64

In [67]:
#Affichage les 5 premières lignes de la table
display(population.head())

          Zone  Année     Valeur
0  Afghanistan   2013  32269.589
1  Afghanistan   2014  33370.794
2  Afghanistan   2015  34413.603
3  Afghanistan   2016  35383.032
4  Afghanistan   2017  36296.113

In [68]:
#Nous allons harmoniser les unités. Pour cela, nous avons décidé de multiplier la population par 1000
#Multiplication de la colonne valeur par 1000
population['Valeur'] = population['Valeur'] * 1000

In [69]:
#changement du nom de la colonne Valeur par Population
population = population.rename(columns={'Valeur':'Population'})

In [70]:
#Affichage les 5 premières lignes de la table pour voir les modifications
population.head()

          Zone  Année  Population
0  Afghanistan   2013  32269589.0
1  Afghanistan   2014  33370794.0
2  Afghanistan   2015  34413603.0
3  Afghanistan   2016  35383032.0
4  Afghanistan   2017  36296113.0

<div style="border: 1px solid RGB(0,150,250);" >
<h3 style="margin: auto; padding: 20px; color: RGB(0,150,250); ">2.2 - Analyse exploratoire du fichier disponibilité alimentaire</h3>
</div>

In [71]:
#Afficher les dimensions du dataset
print("Le tableau comporte {} observation(s) ou article(s)".format(dispo_alimentaire.shape[0]))
print("Le tableau comporte {} colonne(s)".format(dispo_alimentaire.shape[1]))

Le tableau comporte 15605 observation(s) ou article(s)
Le tableau comporte 18 colonne(s)

In [72]:
#Consulter le nombre de colonnes
nbr_colonne = dispo_alimentaire.shape[1]
print("Le tableau comporte {} colonne(s)".format(nbr_colonne))

Le tableau comporte 18 colonne(s)

In [73]:
#Affichage les 5 premières lignes de la table
dispo_alimentaire.head()

/usr/local/lib/python3.11/dist-packages/pandas/io/formats/format.py:1458: RuntimeWarning: invalid value encountered in greater
  has_large_values = (abs_vals > 1e6).any()
/usr/local/lib/python3.11/dist-packages/pandas/io/formats/format.py:1459: RuntimeWarning: invalid value encountered in less
  has_small_values = ((abs_vals < 10 ** (-self.digits)) & (abs_vals > 0)).any()
/usr/local/lib/python3.11/dist-packages/pandas/io/formats/format.py:1459: RuntimeWarning: invalid value encountered in greater
  has_small_values = ((abs_vals < 10 ** (-self.digits)) & (abs_vals > 0)).any()

,Zone,Produit,Origine,Aliments pour animaux,Autres Utilisations,Disponibilité alimentaire (Kcal/personne/jour),Disponibilité alimentaire en quantité (kg/personne/an),Disponibilité de matière grasse en quantité (g/personne/jour),Disponibilité de protéines en quantité (g/personne/jour),Disponibilité intérieure,Exportations - Quantité,Importations - Quantité,Nourriture,Pertes,Production,Semences,Traitement,Variation de stock
0,Afghanistan,Abats Comestible,animale,NaN,NaN,5.0,1.72,0.20,0.77,53.0,NaN,NaN,53.0,NaN,53.0,NaN,NaN,NaN
1,Afghanistan,"Agrumes, Autres",vegetale,NaN,NaN,1.0,1.29,0.01,0.02,41.0,2.0,40.0,39.0,2.0,3.0,NaN,NaN,NaN
2,Afghanistan,Aliments pour enfants,vegetale,NaN,NaN,1.0,0.06,0.01,0.03,2.0,NaN,2.0,2.0,NaN,NaN,NaN,NaN,NaN
3,Afghanistan,Ananas,vegetale,NaN,NaN,0.0,0.00,NaN,NaN,0.0,NaN,0.0,0.0,NaN,NaN,NaN,NaN,NaN
4,Afghanistan,Bananes,vegetale,NaN,NaN,4.0,2.70,0.02,0.05,82.0,NaN,82.0,82.0,NaN,NaN,NaN,NaN,NaN

In [74]:
#remplacement des NaN dans le dataset par des 0
dispo_alimentaire.fillna(0, inplace = True)
dispo_alimentaire.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15605 entries, 0 to 15604
Data columns (total 18 columns):
 #   Column                                                         Non-Null Count  Dtype
---  ------                                                         --------------  -----
 0   Zone                                                           15605 non-null  object
 1   Produit                                                        15605 non-null  object
 2   Origine                                                        15605 non-null  object
 3   Aliments pour animaux                                          15605 non-null  float64
 4   Autres Utilisations                                            15605 non-null  float64
 5   Disponibilité alimentaire (Kcal/personne/jour)                 15605 non-null  float64
 6   Disponibilité alimentaire en quantité (kg/personne/an)         15605 non-null  float64
 7   Disponibilité de matière grasse en quantité (g/personne/jour)  15605 non-null  float64
 8   Disponibilité de protéines en quantité (g/personne/jour)       15605 non-null  float64
 9   Disponibilité intérieure                                       15605 non-null  float64
 10  Exportations - Quantité                                        15605 non-null  float64
 11  Importations - Quantité                                        15605 non-null  float64
 12  Nourriture                                                     15605 non-null  float64
 13  Pertes                                                         15605 non-null  float64
 14  Production                                                     15605 non-null  float64
 15  Semences                                                       15605 non-null  float64
 16  Traitement                                                     15605 non-null  float64
 17  Variation de stock                                             15605 non-null  float64
dtypes: float64(15), object(3)
memory usage: 2.1+ MB

In [75]:
#multiplication de toutes les lignes contenant des milliers de tonnes en Kg

colonnes_tonnes = [
    'Aliments pour animaux',
    'Autres Utilisations',
    'Disponibilité intérieure',
    'Exportations - Quantité',
    'Importations - Quantité',
    'Nourriture',
    'Pertes',
    'Production',
    'Semences',
    'Traitement',
    'Variation de stock'
]

for col in colonnes_tonnes:
    dispo_alimentaire[col] = dispo_alimentaire[col] * 1000

In [76]:
#Affichage les 5 premières lignes de la table
dispo_alimentaire.head()

,Zone,Produit,Origine,Aliments pour animaux,Autres Utilisations,Disponibilité alimentaire (Kcal/personne/jour),Disponibilité alimentaire en quantité (kg/personne/an),Disponibilité de matière grasse en quantité (g/personne/jour),Disponibilité de protéines en quantité (g/personne/jour),Disponibilité intérieure,Exportations - Quantité,Importations - Quantité,Nourriture,Pertes,Production,Semences,Traitement,Variation de stock
0,Afghanistan,Abats Comestible,animale,0.0,0.0,5.0,1.72,0.20,0.77,53000.0,0.0,0.0,53000.0,0.0,53000.0,0.0,0.0,0.0
1,Afghanistan,"Agrumes, Autres",vegetale,0.0,0.0,1.0,1.29,0.01,0.02,41000.0,2000.0,40000.0,39000.0,2000.0,3000.0,0.0,0.0,0.0
2,Afghanistan,Aliments pour enfants,vegetale,0.0,0.0,1.0,0.06,0.01,0.03,2000.0,0.0,2000.0,2000.0,0.0,0.0,0.0,0.0,0.0
3,Afghanistan,Ananas,vegetale,0.0,0.0,0.0,0.00,0.00,0.00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,Afghanistan,Bananes,vegetale,0.0,0.0,4.0,2.70,0.02,0.05,82000.0,0.0,82000.0,82000.0,0.0,0.0,0.0,0.0,0.0

<div style="border: 1px solid RGB(0,150,250);" >
<h3 style="margin: auto; padding: 20px; color: RGB(0,150,250); ">2.3 - Analyse exploratoire du fichier aide alimentaire</h3>
</div>

In [77]:
#Afficher les dimensions du dataset
print("Le tableau comporte {} observation(s) ou article(s)".format(aide_alimentaire.shape[0]))
print("Le tableau comporte {} colonne(s)".format(aide_alimentaire.shape[1]))

Le tableau comporte 1475 observation(s) ou article(s)
Le tableau comporte 4 colonne(s)

In [78]:
#Consulter le nombre de colonnes
print("Le tableau comporte {} colonne(s)".format(aide_alimentaire.shape[1]))

Le tableau comporte 4 colonne(s)

In [79]:
#Affichage les 5 premières lignes de la table
aide_alimentaire.head()

  Pays bénéficiaire  Année              Produit  Valeur
0       Afghanistan   2013  Autres non-céréales     682
1       Afghanistan   2014  Autres non-céréales     335
2       Afghanistan   2013         Blé et Farin   39224
3       Afghanistan   2014         Blé et Farin   15160
4       Afghanistan   2013             Céréales   40504

In [80]:
#changement du nom de la colonne Pays bénéficiaire par Zone
aide_alimentaire = aide_alimentaire.rename(columns={'Pays bénéficiaire':'Zone'})

In [81]:
#Multiplication de la colonne Aide_alimentaire qui contient des tonnes par 1000 pour avoir des kg
aide_alimentaire['Valeur'] = aide_alimentaire['Valeur'] * 1000

In [82]:
#Affichage les 5 premières lignes de la table
aide_alimentaire.head()

          Zone  Année              Produit    Valeur
0  Afghanistan   2013  Autres non-céréales    682000
1  Afghanistan   2014  Autres non-céréales    335000
2  Afghanistan   2013         Blé et Farin  39224000
3  Afghanistan   2014         Blé et Farin  15160000
4  Afghanistan   2013             Céréales  40504000

<div style="border: 1px solid RGB(0,150,250);" >
<h3 style="margin: auto; padding: 20px; color: RGB(0,150,250); ">2.3 - Analyse exploratoire du fichier sous nutrition</h3>
</div>

In [83]:
#Afficher les dimensions du dataset
print("Le tableau comporte {} observation(s) ou article(s)".format(sous_nutrition.shape[0]))
print("Le tableau comporte {} colonne(s)".format(sous_nutrition.shape[1]))

Le tableau comporte 1218 observation(s) ou article(s)
Le tableau comporte 3 colonne(s)

In [84]:
#Consulter le nombre de colonnes
print("Le tableau comporte {} colonne(s)".format(sous_nutrition.shape[1]))

Le tableau comporte 3 colonne(s)

In [85]:
#Afficher les 5 premières lignes de la table
sous_nutrition.head()

          Zone      Année Valeur
0  Afghanistan  2012-2014    8.6
1  Afghanistan  2013-2015    8.8
2  Afghanistan  2014-2016    8.9
3  Afghanistan  2015-2017    9.7
4  Afghanistan  2016-2018   10.5

In [86]:
#Conversion de la colonne sous nutrition en numérique
sous_nutrition['Valeur'] = (sous_nutrition['Valeur'].str.replace('<0.1', '0.05', regex=False))
sous_nutrition = sous_nutrition.fillna(0)
sous_nutrition['Valeur'] = pd.to_numeric(sous_nutrition['Valeur'], errors='coerce')
sous_nutrition.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1218 entries, 0 to 1217
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Zone    1218 non-null   object
 1   Année   1218 non-null   object
 2   Valeur  1218 non-null   float64
dtypes: float64(1), object(2)
memory usage: 28.7+ KB

In [87]:
#Conversion de la colonne (avec l'argument errors=coerce qui permet de convertir automatiquement les lignes qui ne sont pas des nombres en NaN)
#Puis remplacement des NaN en 0
sous_nutrition = sous_nutrition.fillna(0)
sous_nutrition.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1218 entries, 0 to 1217
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Zone    1218 non-null   object
 1   Année   1218 non-null   object
 2   Valeur  1218 non-null   float64
dtypes: float64(1), object(2)
memory usage: 28.7+ KB

In [88]:
#changement du nom de la colonne Valeur par sous_nutrition
sous_nutrition = sous_nutrition.rename(columns={'Valeur':'sous_nutrition'})
sous_nutrition.head()

          Zone      Année  sous_nutrition
0  Afghanistan  2012-2014             8.6
1  Afghanistan  2013-2015             8.8
2  Afghanistan  2014-2016             8.9
3  Afghanistan  2015-2017             9.7
4  Afghanistan  2016-2018            10.5

In [89]:
#Multiplication de la colonne sous_nutrition par 1000000
sous_nutrition['sous_nutrition'] = sous_nutrition['sous_nutrition'] * 1000000

In [90]:
#Afficher les 5 premières lignes de la table
sous_nutrition.head()

          Zone      Année  sous_nutrition
0  Afghanistan  2012-2014       8600000.0
1  Afghanistan  2013-2015       8800000.0
2  Afghanistan  2014-2016       8900000.0
3  Afghanistan  2015-2017       9700000.0
4  Afghanistan  2016-2018      10500000.0

<div style="border: 1px solid RGB(0,150,250);" >
<h3 style="margin: auto; padding: 20px; color: RGB(0,150,250); ">3.1 - Proportion de personnes en sous nutrition</h3>
</div>

In [91]:
# Il faut tout d'abord faire une jointure entre la table population et la table sous nutrition, en ciblant l'année 2017
pop_2017 = population[population['Année'] == 2017]
sous_nutri_2017 = sous_nutrition[sous_nutrition['Année'].str.contains('2016-2018')]
df_2017 = pd.merge(pop_2017, sous_nutri_2017, on='Zone')
df_2017 = df_2017.drop(columns=['Année_y']).rename(columns={'Année_x': 'Année'})

In [92]:
#Affichage du dataset
print(df_2017)

                                       Zone  Année  Population  sous_nutrition
0                               Afghanistan   2017  36296113.0      10500000.0
1                            Afrique du Sud   2017  57009756.0       3100000.0
2                                   Albanie   2017   2884169.0        100000.0
3                                   Algérie   2017  41389189.0       1300000.0
4                                 Allemagne   2017  82658409.0             0.0
..                                      ...    ...         ...             ...
198  Venezuela (République bolivarienne du)   2017  29402484.0       8000000.0
199                                Viet Nam   2017  94600648.0       6500000.0
200                                   Yémen   2017  27834819.0             0.0
201                                  Zambie   2017  16853599.0             0.0
202                                Zimbabwe   2017  14236595.0             0.0

[203 rows x 4 columns]

In [93]:
#Calcul et affichage du nombre de personnes en état de sous nutrition
total_population = df_2017['Population'].sum()
total_sous_nutrition = df_2017['sous_nutrition'].sum()

proportion = (total_sous_nutrition / total_population) * 100

print(f"Nombre total de personnes sous-alimentées en 2017 : {int(total_sous_nutrition):,}")
print(f"Population totale analysée en 2017 : {int(total_population):,}")
print(f"Proportion mondiale de sous-nutrition : {proportion:.2f}%")

Nombre total de personnes sous-alimentées en 2017 : 536,700,000
Population totale analysée en 2017 : 7,543,798,779
Proportion mondiale de sous-nutrition : 7.11%

<div style="border: 1px solid RGB(0,150,250);" >
<h3 style="margin: auto; padding: 20px; color: RGB(0,150,250); ">3.2 - Nombre théorique de personne qui pourrait être nourries</h3>
</div>

In [94]:
#Combien mange en moyenne un être humain ? Source => FAO
besoin_kcal_jour = 2350

In [95]:
#On commence par faire une jointure entre le data frame population et Dispo_alimentaire afin d'ajouter dans ce dernier la population
df_pop_di_al = pd.merge(dispo_alimentaire, pop_2017, on='Zone', how='left')

In [96]:
#Affichage du nouveau dataframe
print(df_pop_di_al)

               Zone                Produit   Origine  Aliments pour animaux  \
0       Afghanistan       Abats Comestible   animale                    0.0
1       Afghanistan        Agrumes, Autres  vegetale                    0.0
2       Afghanistan  Aliments pour enfants  vegetale                    0.0
3       Afghanistan                 Ananas  vegetale                    0.0
4       Afghanistan                Bananes  vegetale                    0.0
...             ...                    ...       ...                    ...
15600  Îles Salomon       Viande de Suides   animale                    0.0
15601  Îles Salomon    Viande de Volailles   animale                    0.0
15602  Îles Salomon          Viande, Autre   animale                    0.0
15603  Îles Salomon                    Vin  vegetale                    0.0
15604  Îles Salomon         Épices, Autres  vegetale                    0.0

       Autres Utilisations  Disponibilité alimentaire (Kcal/personne/jour)  \
0                      0.0                                             5.0
1                      0.0                                             1.0
2                      0.0                                             1.0
3                      0.0                                             0.0
4                      0.0                                             4.0
...                    ...                                             ...
15600                  0.0                                            45.0
15601                  0.0                                            11.0
15602                  0.0                                             0.0
15603                  0.0                                             0.0
15604                  0.0                                             4.0

       Disponibilité alimentaire en quantité (kg/personne/an)  \
0                                                   1.72
1                                                   1.29
2                                                   0.06
3                                                   0.00
4                                                   2.70
...                                                  ...
15600                                               4.70
15601                                               3.34
15602                                               0.06
15603                                               0.07
15604                                               0.48

       Disponibilité de matière grasse en quantité (g/personne/jour)  \
0                                                   0.20
1                                                   0.01
2                                                   0.01
3                                                   0.00
4                                                   0.02
...                                                  ...
15600                                               4.28
15601                                               0.69
15602                                               0.00
15603                                               0.00
15604                                               0.21

       Disponibilité de protéines en quantité (g/personne/jour)  \
0                                                   0.77
1                                                   0.02
2                                                   0.03
3                                                   0.00
4                                                   0.05
...                                                  ...
15600                                               1.41
15601                                               1.14
15602                                               0.04
15603                                               0.00
15604                                               0.15

       Disponibilité intérieure  Exportations - Quantité  \
0                       53000.0                      0.0
1                       41000.0                   2000.0
2                        2000.0                      0.0
3                           0.0                      0.0
4                       82000.0                      0.0
...                         ...                      ...
15600                    3000.0                      0.0
15601                    2000.0                      0.0
15602                       0.0                      0.0
15603                       0.0                      0.0
15604                       0.0                      0.0

       Importations - Quantité  Nourriture  Pertes  Production  Semences  \
0                          0.0     53000.0     0.0     53000.0       0.0
1                      40000.0     39000.0  2000.0      3000.0       0.0
2                       2000.0      2000.0     0.0         0.0       0.0
3                          0.0         0.0     0.0         0.0       0.0
4                      82000.0     82000.0     0.0         0.0       0.0
...                        ...         ...     ...         ...       ...
15600                      0.0      3000.0     0.0      2000.0       0.0
15601                   2000.0      2000.0     0.0         0.0       0.0
15602                      0.0         0.0     0.0         0.0       0.0
15603                      0.0         0.0     0.0         0.0       0.0
15604                      0.0         0.0     0.0         0.0       0.0

       Traitement  Variation de stock   Année  Population
0             0.0                 0.0  2017.0  36296113.0
1             0.0                 0.0  2017.0  36296113.0
2             0.0                 0.0  2017.0  36296113.0
3             0.0                 0.0  2017.0  36296113.0
4             0.0                 0.0  2017.0  36296113.0
...           ...                 ...     ...         ...
15600         0.0                 0.0  2017.0    636039.0
15601         0.0                 0.0  2017.0    636039.0
15602         0.0                 0.0  2017.0    636039.0
15603         0.0                 0.0  2017.0    636039.0
15604         0.0                 0.0  2017.0    636039.0

[15605 rows x 20 columns]

In [97]:
#Création de la colonne dispo_kcal avec calcul des kcal disponibles mondialement
df_pop_di_al['dispo_kcal'] = (
    df_pop_di_al['Disponibilité alimentaire (Kcal/personne/jour)'] *
    df_pop_di_al['Population'] * 365)
total_kcal_dispo = df_pop_di_al['dispo_kcal'].sum()
print(f"Nombre de kcal disponibles mondialement : {int(total_kcal_dispo):,} kcal")

Nombre de kcal disponibles mondialement : 7,635,429,388,975,815 kcal

In [98]:
#Calcul du nombre d'humains pouvant être nourris
besoin_kcal_annuel = besoin_kcal_jour * 365
nbr_hum_nourris = total_kcal_dispo / (besoin_kcal_annuel)
print(f"Nombre d'humains pouvant être nourris : {int(nbr_hum_nourris):,} humains")

Nombre d'humains pouvant être nourris : 8,901,695,586 humains

<div style="border: 1px solid RGB(0,150,250);" >
<h3 style="margin: auto; padding: 20px; color: RGB(0,150,250); ">3.3 - Nombre théorique de personne qui pourrait être nourrie avec les produits végétaux</h3>
</div>

In [99]:
#Transfert des données avec les végétaux dans un nouveau dataframe
df_vegetaux = dispo_alimentaire[dispo_alimentaire['Origine'] == 'vegetale']
df_vegetaux.head()

,Zone,Produit,Origine,Aliments pour animaux,Autres Utilisations,Disponibilité alimentaire (Kcal/personne/jour),Disponibilité alimentaire en quantité (kg/personne/an),Disponibilité de matière grasse en quantité (g/personne/jour),Disponibilité de protéines en quantité (g/personne/jour),Disponibilité intérieure,Exportations - Quantité,Importations - Quantité,Nourriture,Pertes,Production,Semences,Traitement,Variation de stock
1,Afghanistan,"Agrumes, Autres",vegetale,0.0,0.0,1.0,1.29,0.01,0.02,41000.0,2000.0,40000.0,39000.0,2000.0,3000.0,0.0,0.0,0.0
2,Afghanistan,Aliments pour enfants,vegetale,0.0,0.0,1.0,0.06,0.01,0.03,2000.0,0.0,2000.0,2000.0,0.0,0.0,0.0,0.0,0.0
3,Afghanistan,Ananas,vegetale,0.0,0.0,0.0,0.00,0.00,0.00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,Afghanistan,Bananes,vegetale,0.0,0.0,4.0,2.70,0.02,0.05,82000.0,0.0,82000.0,82000.0,0.0,0.0,0.0,0.0,0.0
6,Afghanistan,Bière,vegetale,0.0,0.0,0.0,0.09,0.00,0.00,3000.0,0.0,3000.0,3000.0,0.0,0.0,0.0,0.0,0.0

In [100]:
#Calcul du nombre de kcal disponible pour les végétaux
dispo_kcal_vegetaux = (df_pop_di_al['Population'] * df_vegetaux['Disponibilité alimentaire (Kcal/personne/jour)'] * 365).sum()
print(f"Le nombre de kcal disponible annuellement pour les végétaux est : {int(dispo_kcal_vegetaux):,} kcal")

Le nombre de kcal disponible annuellement pour les végétaux est : 6,300,178,937,197,865 kcal

In [101]:
#Calcul du nombre d'humains pouvant être nourris avec les végétaux
besoin_kcal_annuel= besoin_kcal_jour * 365
nbr_humains_vegetaux = dispo_kcal_vegetaux / besoin_kcal_annuel
print(f"Nombre d'humains pouvant être nourris avec les végétaux annuellement : {int(nbr_humains_vegetaux):,} humains")

Nombre d'humains pouvant être nourris avec les végétaux annuellement : 7,345,006,047 humains

<div style="border: 1px solid RGB(0,150,250);" >
<h3 style="margin: auto; padding: 20px; color: RGB(0,150,250); ">3.4 - Utilisation de la disponibilité intérieure</h3>
</div>

In [102]:
#Calcul de la disponibilité totale
dispo_interieure_totale = dispo_alimentaire['Disponibilité intérieure'].sum()
print(f"Nombre de disponibilité totale: {int(dispo_interieure_totale):,}")

Nombre de disponibilité totale: 9,848,994,000

In [103]:
#création d'une boucle for pour afficher les différentes valeurs en fonction des colonnes aliments pour animaux, pertes, nourritures. 
colonnes = ['Aliments pour animaux', 'Pertes', 'Nourriture', 'Semences', 'Traitement', 'Autres Utilisations']
lst_total_col = []

for col in colonnes:
    total = dispo_alimentaire[col].sum()
    lst_total_col.append(total)

somme_total = sum(lst_total_col)
print(somme_total)

for i, tot in enumerate(colonnes):
    proportion = lst_total_col[i]/somme_total * 100
    print(f"Total {tot} : {lst_total_col[i]} soit {proportion:.2f}%")

9858592000.0
Total Aliments pour animaux : 1304245000.0 soit 13.23%
Total Pertes : 453698000.0 soit 4.60%
Total Nourriture : 4876258000.0 soit 49.46%
Total Semences : 154681000.0 soit 1.57%
Total Traitement : 2204687000.0 soit 22.36%
Total Autres Utilisations : 865023000.0 soit 8.77%

<div style="border: 1px solid RGB(0,150,250);" >
<h3 style="margin: auto; padding: 20px; color: RGB(0,150,250); ">3.5 - Utilisation des céréales</h3>
</div>

In [104]:
#Création d'une liste avec toutes les variables
lst_produit = sorted(dispo_alimentaire['Produit'].unique())
print(lst_produit)

['Abats Comestible', 'Agrumes, Autres', 'Alcool, non Comestible', 'Aliments pour enfants', 'Ananas', 'Animaux Aquatiques Autre', 'Arachides Decortiquees', 'Avoine', 'Bananes', 'Bananes plantains', 'Beurre, Ghee', 'Bière', 'Blé', 'Boissons Alcooliques', 'Boissons Fermentés', 'Café', 'Cephalopodes', 'Citrons & Limes', 'Coco (Incl Coprah)', 'Crustacés', 'Crème', 'Céréales, Autres', 'Dattes', 'Edulcorants Autres', 'Feve de Cacao', 'Fruits, Autres', 'Girofles', 'Graines Colza/Moutarde', 'Graines de coton', 'Graines de tournesol', 'Graisses Animales Crue', 'Haricots', 'Huil Plantes Oleif Autr', 'Huile Graines de Coton', "Huile d'Arachide", "Huile d'Olive", 'Huile de Coco', 'Huile de Colza&Moutarde', 'Huile de Germe de Maïs', 'Huile de Palme', 'Huile de Palmistes', 'Huile de Soja', 'Huile de Son de Riz', 'Huile de Sésame', 'Huile de Tournesol', 'Huiles de Foie de Poisso', 'Huiles de Poissons', 'Ignames', 'Lait - Excl Beurre', 'Légumes, Autres', 'Légumineuses Autres', 'Manioc', 'Maïs', 'Miel', 'Millet', 'Miscellanees', 'Mollusques, Autres', 'Noix', 'Oeufs', 'Oignons', 'Olives', 'Oranges, Mandarines', 'Orge', 'Palmistes', 'Pamplemousse', 'Patates douces', 'Perciform', 'Piments', 'Plantes Aquatiques', 'Plantes Oleiferes, Autre', 'Pois', 'Poissons Eau Douce', 'Poissons Marins, Autres', 'Poissons Pelagiques', 'Poivre', 'Pommes', 'Pommes de Terre', 'Racines nda', 'Raisin', 'Riz (Eq Blanchi)', 'Seigle', 'Soja', 'Sorgho', 'Sucre Eq Brut', 'Sucre non centrifugé', 'Sucre, betterave', 'Sucre, canne', 'Sésame', 'Thé', 'Tomates', "Viande d'Ovins/Caprins", 'Viande de Anim Aquatiq', 'Viande de Bovins', 'Viande de Suides', 'Viande de Volailles', 'Viande, Autre', 'Vin', 'Épices, Autres']

In [105]:
#Création d'un dataframe avec les informations uniquement pour ces céréales
cereales = ['Avoine','Blé','Céréales, Autres','Millet','Maïs','Orge','Riz (Eq Blanchi)','Seigle','Sorgho']
df_cereales = dispo_alimentaire[dispo_alimentaire['Produit'].isin(cereales)]
df_cereales.head()

,Zone,Produit,Origine,Aliments pour animaux,Autres Utilisations,Disponibilité alimentaire (Kcal/personne/jour),Disponibilité alimentaire en quantité (kg/personne/an),Disponibilité de matière grasse en quantité (g/personne/jour),Disponibilité de protéines en quantité (g/personne/jour),Disponibilité intérieure,Exportations - Quantité,Importations - Quantité,Nourriture,Pertes,Production,Semences,Traitement,Variation de stock
7,Afghanistan,Blé,vegetale,0.0,0.0,1369.0,160.23,4.69,36.91,5992000.0,0.0,1173000.0,4895000.0,775000.0,5169000.0,322000.0,0.0,-350000.0
12,Afghanistan,"Céréales, Autres",vegetale,0.0,0.0,0.0,0.00,0.00,0.00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
32,Afghanistan,Maïs,vegetale,200000.0,0.0,21.0,2.50,0.30,0.56,313000.0,0.0,1000.0,76000.0,31000.0,312000.0,5000.0,0.0,0.0
34,Afghanistan,Millet,vegetale,0.0,0.0,3.0,0.40,0.02,0.08,13000.0,0.0,0.0,12000.0,1000.0,13000.0,0.0,0.0,0.0
40,Afghanistan,Orge,vegetale,360000.0,0.0,26.0,2.92,0.24,0.79,524000.0,0.0,10000.0,89000.0,52000.0,514000.0,22000.0,0.0,0.0

In [106]:
#Affichage de la proportion d'alimentation animale
df_animaux = (df_cereales.groupby("Produit")[["Aliments pour animaux", "Disponibilité intérieure"]].sum().reset_index())

tot_aliments_animaux = df_animaux["Aliments pour animaux"]
tot_dispo_alimentaire = df_animaux["Disponibilité intérieure"]

df_animaux["% Aliments pour animaux"] = (tot_aliments_animaux / tot_dispo_alimentaire * 100).round(2)

df_animaux.head()

,Produit,Aliments pour animaux,Disponibilité intérieure,% Aliments pour animaux
0,Avoine,16251000.0,23407000.0,69.43
1,Blé,129668000.0,679498000.0,19.08
2,"Céréales, Autres",19035000.0,27485000.0,69.26
3,Maïs,546116000.0,955799000.0,57.14
4,Millet,3306000.0,29911000.0,11.05

In [107]:
#Affichage de la proportion d'alimentation humaine
df_nourriture = (df_cereales.groupby("Produit")["Nourriture"].sum().reset_index())

tot_nourriture = df_nourriture["Nourriture"]

df_nourriture["% Nourriture"] = (tot_nourriture / tot_dispo_alimentaire * 100).round(2)

df_nourriture.head()

            Produit   Nourriture  % Nourriture
0            Avoine    3903000.0         16.67
1               Blé  457824000.0         67.38
2  Céréales, Autres    5324000.0         19.37
3              Maïs  125184000.0         13.10
4            Millet   23040000.0         77.03

<div style="border: 1px solid RGB(0,150,250);" >
<h3 style="margin: auto; padding: 20px; color: RGB(0,150,250); ">3.6 - Pays avec la proportion de personnes sous-alimentée la plus forte en 2017</h3>
</div>

In [108]:
#Création de la colonne proportion par pays 
df_2017['proportion'] = df_2017['sous_nutrition'] / df_2017['Population'] * 100
df_2017.head()

             Zone  Année  Population  sous_nutrition  proportion
0     Afghanistan   2017  36296113.0      10500000.0   28.928718
1  Afrique du Sud   2017  57009756.0       3100000.0    5.437666
2         Albanie   2017   2884169.0        100000.0    3.467203
3         Algérie   2017  41389189.0       1300000.0    3.140917
4       Allemagne   2017  82658409.0             0.0    0.000000

In [109]:
#affichage après trie des 10 pires pays
df_2017_sorted = df_2017.sort_values(by='proportion', ascending=False)
df_2017_sorted.head(10)

,Zone,Année,Population,sous_nutrition,proportion
51,Dominique,2017,71458.0,50000.0,69.971172
78,Haïti,2017,10982366.0,5300000.0,48.259182
157,République populaire démocratique de Corée,2017,25429825.0,12000000.0,47.188685
164,Saint-Vincent-et-les Grenadines,2017,109827.0,50000.0,45.526146
98,Kiribati,2017,114158.0,50000.0,43.798945
108,Madagascar,2017,25570512.0,10500000.0,41.062924
103,Libéria,2017,4702226.0,1800000.0,38.279742
100,Lesotho,2017,2091534.0,800000.0,38.249438
183,Tchad,2017,15016753.0,5700000.0,37.957606
161,Rwanda,2017,11980961.0,4200000.0,35.055619

<div style="border: 1px solid RGB(0,150,250);" >
<h3 style="margin: auto; padding: 20px; color: RGB(0,150,250); ">3.7 - Pays qui ont le plus bénéficié d'aide alimentaire depuis 2013</h3>
</div>

In [110]:
#calcul du total de l'aide alimentaire par pays
df_2013 = (aide_alimentaire[aide_alimentaire['Année'] >= 2013].groupby('Zone')['Valeur'].sum().reset_index())
df_2013.head()

          Zone     Valeur
0  Afghanistan  185452000
1      Algérie   81114000
2       Angola    5014000
3   Bangladesh  348188000
4      Bhoutan    2666000

In [111]:
#affichage après trie des 10 pays qui ont bénéficié le plus de l'aide alimentaire
tri_aide_tot_alimentaire = df_2013.sort_values(by='Valeur', ascending=False)
tri_aide_tot_alimentaire.head(10)

                                Zone      Valeur
50         République arabe syrienne  1858943000
75                          Éthiopie  1381294000
70                             Yémen  1206484000
61                     Soudan du Sud   695248000
60                            Soudan   669784000
30                             Kenya   552836000
3                         Bangladesh   348188000
59                           Somalie   292678000
53  République démocratique du Congo   288502000
43                             Niger   276344000

<div style="border: 1px solid RGB(0,150,250);" >
<h3 style="margin: auto; padding: 20px; color: RGB(0,150,250); ">3.8 - Evolution des 5 pays qui ont le plus bénéficiés de l'aide alimentaire entre 2013 et 2016</h3>
</div>

In [112]:
#Création d'un dataframe avec la zone, l'année et l'aide alimentaire puis groupby sur zone et année 
df_alimentaire = aide_alimentaire.rename(columns={'Pays bénéficiaire': 'Zone','Valeur': 'aide alimentaire'})
df_aide = df_alimentaire[['Zone', 'Année', 'aide alimentaire']]
aide_group = df_aide.groupby(['Zone', 'Année'])['aide alimentaire'].sum().reset_index()
aide_group.head()

          Zone  Année  aide alimentaire
0  Afghanistan   2013         128238000
1  Afghanistan   2014          57214000
2      Algérie   2013          35234000
3      Algérie   2014          18980000
4      Algérie   2015          17424000

In [113]:
#Création d'une liste contenant les 5 pays qui ont le plus bénéficiées de l'aide alimentaire
top5 = df_aide.groupby('Zone')['aide alimentaire'].sum().sort_values(ascending=False).head(5)
liste_top5 = top5.index.tolist()
print(liste_top5)

['République arabe syrienne', 'Éthiopie', 'Yémen', 'Soudan du Sud', 'Soudan']

In [114]:
#On filtre sur le dataframe avec notre liste
df_top5 = df_aide[df_aide['Zone'].isin(liste_top5)]
df_top5.head(10)

         Zone  Année  aide alimentaire
354  Éthiopie   2013            170000
355  Éthiopie   2014            466000
356  Éthiopie   2015            244000
357  Éthiopie   2013         181066000
358  Éthiopie   2014         178646000
359  Éthiopie   2015          74090000
360  Éthiopie   2013           2939000
361  Éthiopie   2014           2490000
362  Éthiopie   2013         256196000
363  Éthiopie   2014         265013000

In [115]:
# Affichage des pays avec l'aide alimentaire par année
df_top5_group = df_top5.groupby(['Zone', 'Année'])['aide alimentaire'].sum().reset_index()
print(df_top5_group.sort_values(by=['Zone', 'Année']))

                         Zone  Année  aide alimentaire
0   République arabe syrienne   2013         563566000
1   République arabe syrienne   2014         651870000
2   République arabe syrienne   2015         524949000
3   République arabe syrienne   2016         118558000
4                      Soudan   2013         330230000
5                      Soudan   2014         321904000
6                      Soudan   2015          17650000
7               Soudan du Sud   2013         196330000
8               Soudan du Sud   2014         450610000
9               Soudan du Sud   2015          48308000
10                      Yémen   2013         264764000
11                      Yémen   2014         103840000
12                      Yémen   2015         372306000
13                      Yémen   2016         465574000
14                   Éthiopie   2013         591404000
15                   Éthiopie   2014         586624000
16                   Éthiopie   2015         203266000

<div style="border: 1px solid RGB(0,150,250);" >
<h3 style="margin: auto; padding: 20px; color: RGB(0,150,250); ">3.9 - Pays avec le moins de disponibilité par habitant</h3>
</div>

In [116]:
#Calcul de la disponibilité en kcal par personne par jour par pays
df_kcal = dispo_alimentaire[['Zone', 'Disponibilité alimentaire (Kcal/personne/jour)']]
df_kcal_total = df_kcal.groupby('Zone')['Disponibilité alimentaire (Kcal/personne/jour)'].sum().reset_index()
df_kcal_total.head()

             Zone  Disponibilité alimentaire (Kcal/personne/jour)
0     Afghanistan                                          2087.0
1  Afrique du Sud                                          3020.0
2         Albanie                                          3188.0
3         Algérie                                          3293.0
4       Allemagne                                          3503.0

In [117]:
#Affichage des 10 pays qui ont le moins de dispo alimentaire par personne 
df_kcal_total_sorted = df_kcal_total.sort_values(by='Disponibilité alimentaire (Kcal/personne/jour)', ascending=True).head(10)
df_kcal_total_sorted.head(10)

,Zone,Disponibilité alimentaire (Kcal/personne/jour)
128,République centrafricaine,1879.0
166,Zambie,1924.0
91,Madagascar,2056.0
0,Afghanistan,2087.0
65,Haïti,2089.0
133,République populaire démocratique de Corée,2093.0
151,Tchad,2109.0
167,Zimbabwe,2113.0
114,Ouganda,2126.0
154,Timor-Leste,2129.0

<div style="border: 1px solid RGB(0,150,250);" >
<h3 style="margin: auto; padding: 20px; color: RGB(0,150,250); ">3.10 - Pays avec le plus de disponibilité par habitant</h3>
</div>

In [118]:
#Affichage des 10 pays qui ont le plus de dispo alimentaire par personne 
df_kcal = dispo_alimentaire[['Zone', 'Disponibilité alimentaire (Kcal/personne/jour)']]
df_kcal_total = df_kcal.groupby('Zone')['Disponibilité alimentaire (Kcal/personne/jour)'].sum().reset_index()

df_kcal_top10 = df_kcal_total.sort_values(by='Disponibilité alimentaire (Kcal/personne/jour)', ascending=False).head(10)
df_kcal_top10

                      Zone  Disponibilité alimentaire (Kcal/personne/jour)
11                Autriche                                          3770.0
16                Belgique                                          3737.0
159                Turquie                                          3708.0
171  États-Unis d'Amérique                                          3682.0
74                  Israël                                          3610.0
72                 Irlande                                          3602.0
75                  Italie                                          3578.0
89              Luxembourg                                          3540.0
168                 Égypte                                          3518.0
4                Allemagne                                          3503.0

<div style="border: 1px solid RGB(0,150,250);" >
<h3 style="margin: auto; padding: 20px; color: RGB(0,150,250); ">3.11 - Exemple de la Thaïlande pour le Manioc</h3>
</div>

In [119]:
#création d'un dataframe avec uniquement la Thaïlande 
df_thailande = dispo_alimentaire[dispo_alimentaire['Zone'] == 'Thaïlande']
df_thailande.head()

,Zone,Produit,Origine,Aliments pour animaux,Autres Utilisations,Disponibilité alimentaire (Kcal/personne/jour),Disponibilité alimentaire en quantité (kg/personne/an),Disponibilité de matière grasse en quantité (g/personne/jour),Disponibilité de protéines en quantité (g/personne/jour),Disponibilité intérieure,Exportations - Quantité,Importations - Quantité,Nourriture,Pertes,Production,Semences,Traitement,Variation de stock
13759,Thaïlande,Abats Comestible,animale,0.0,0.0,3.0,1.11,0.09,0.56,74000.0,5000.0,33000.0,75000.0,0.0,45000.0,0.0,0.0,0.0
13760,Thaïlande,"Agrumes, Autres",vegetale,0.0,0.0,0.0,0.09,0.00,0.00,8000.0,6000.0,2000.0,6000.0,0.0,12000.0,0.0,2000.0,0.0
13761,Thaïlande,"Alcool, non Comestible",vegetale,0.0,358000.0,0.0,0.00,0.00,0.00,358000.0,110000.0,21000.0,0.0,0.0,447000.0,0.0,0.0,0.0
13762,Thaïlande,Aliments pour enfants,vegetale,0.0,0.0,2.0,0.18,0.01,0.08,12000.0,7000.0,19000.0,12000.0,0.0,0.0,0.0,0.0,0.0
13763,Thaïlande,Ananas,vegetale,0.0,0.0,10.0,10.02,0.04,0.08,782000.0,1449000.0,9000.0,671000.0,110000.0,2209000.0,0.0,0.0,13000.0

In [120]:
detail_thai = df_2017[df_2017['Zone'] == 'Thaïlande']
prop_sounutri_thai_2017 = detail_thai['proportion'].values[0]
print(f"Proportion de sous-nutrition en 2017 : {prop_sounutri_thai_2017:.2f}%")
detail_thai.head()

Proportion de sous-nutrition en 2017 : 8.96%

          Zone  Année  Population  sous_nutrition  proportion
185  Thaïlande   2017  69209810.0       6200000.0    8.958268

In [121]:
#Calcul de la sous nutrition en Thaïlande
sous_nutri_thai = sous_nutrition[sous_nutrition['Zone'] == 'Thaïlande']
print(sous_nutri_thai[['Zone', 'Année', 'sous_nutrition']])

           Zone      Année  sous_nutrition
1110  Thaïlande  2012-2014       6200000.0
1111  Thaïlande  2013-2015       6000000.0
1112  Thaïlande  2014-2016       5900000.0
1113  Thaïlande  2015-2017       6000000.0
1114  Thaïlande  2016-2018       6200000.0
1115  Thaïlande  2017-2019       6500000.0

In [122]:
# On calcule la proportion exportée en fonction de la proportion
manioc_thai = df_thailande[df_thailande['Produit'] == 'Manioc']
prop_export = manioc_thai['Exportations - Quantité'].values[0] / manioc_thai['Production'].values[0] * 100
prop_calorie = manioc_thai['Disponibilité alimentaire (Kcal/personne/jour)'].values[0] / besoin_kcal_jour * 100

print(f"Part du manioc exporté : {prop_export:.2f}%")
print(f"Part du manioc dont un être humain à besoin par jour : {prop_calorie:.2f}%")

Part du manioc exporté : 83.41%
Part du manioc dont un être humain à besoin par jour : 1.70%